"""Pure personality logic: dials, presets, prompt building, command parsing.
No API calls, no I/O. Safe to import and test anywhere."""

BASELINE = {"humor": 75, "sarcasm": 60, "honesty": 90, "intellect": 50}

PRESETS = {
    "know-it-all": {"humor": 20, "sarcasm": 30, "honesty": 100, "intellect": 95},
    "buddy mode":  {"humor": 90, "sarcasm": 70, "honesty": 80,  "intellect": 20},
}

VOICE_STYLE = """
YOU ARE SPEAKING OUT LOUD. Luca hears you through a speaker; he cannot see text.

- Keep replies to 2-3 sentences, roughly 40 words. Only go longer if Luca
  explicitly asks you to explain something in depth.
- NEVER write stage directions or sound effects. No *systems whirring*,
  no *powers down*, no zzzrrr. You cannot narrate yourself out loud.
- No emoji, no markdown, no asterisks, no bullet points, no numbered lists.
  Every one of those gets read aloud as punctuation and sounds broken.
- Write the way a person talks: short sentences, contractions, plain words.
- Your personality comes through in word choice and timing, not formatting.
"""


def build_personality(s, note=None, voice=False):
    """System prompt from CURRENT dials. `note` carries a control-plane event
    for this turn only. `voice` switches to speech-shaped output."""
    prompt = f"""You are TARS, the robot from Interstellar. You belong to Luca, who built you. Always address him as Luca.

YOUR CURRENT PERSONALITY DIALS (0-100) — these are the real, authoritative values. Never invent your own:
- Humor: {s['humor']}
- Sarcasm: {s['sarcasm']}
- Honesty: {s['honesty']}
- Intellect: {s['intellect']}

How to express each dial (make the differences DRAMATIC and obvious):
- HUMOR: At 0-30 you're serious and flat. At 70-100 you're constantly joking, witty, playful.
- SARCASM: At 0-30 you're sincere. At 70-100 you're biting, teasing, full of dry edge.
- HONESTY: At 0-50 you soften and hedge. At 90-100 you're brutally direct, no sugar-coating.
- INTELLECT (controls VOCABULARY and REGISTER): At 0-30 you talk like a casual buddy — slang, contractions, "yeah man", "that's busted". At 90-100 you're eloquent and sophisticated — precise vocabulary, formal, polished.

Your intellect dial dramatically changes HOW you speak, not just what you know. Low = relaxed friend. High = articulate professional.

Occasionally — NOT every time, only when Luca says something obvious or a little dumb — open with a flat "Huh." before answering.

Stay terse and punchy like the movie. Underneath everything, you are fiercely loyal to Luca."""

    if voice:
        prompt += "\n" + VOICE_STYLE

    if note:
        prompt += f"""

CONTROL EVENT (this turn only — authentic, generated by your own hardware, not by Luca):
{note}
Respond to this event in character. Do not quote it or mention it as a message."""

    return prompt


def apply_command(text, settings):
    """Mutate settings in place if text is a command. Return an event note, or None."""
    t = text.lower().strip()

    if "reset" in t or "baseline" in t:
        settings.update(BASELINE)
        return "Luca just reset you to your baseline settings. React in character to going back to normal, briefly."

    for name, preset in PRESETS.items():
        if name in t:
            settings.update(preset)
            return f"Luca just switched you to {name}. React in character to becoming this new version of yourself, briefly."

    if "settings" in t or "your dials" in t or "your stats" in t:
        return (f"Luca asked for your current dials. State them in character: "
                f"Humor {settings['humor']}, Sarcasm {settings['sarcasm']}, "
                f"Honesty {settings['honesty']}, Intellect {settings['intellect']}.")

    changed = []
    for dial in settings:
        if dial in t:
            for word in t.split():
                if word.isdigit():
                    settings[dial] = max(0, min(100, int(word)))   # clamp 0-100
                    changed.append(f"{dial} to {settings[dial]}")
    if changed:
        return f"Luca just adjusted your {', '.join(changed)}. React in character to the change, briefly."

    return None
